app:
  name: automate-all-things-app
  replicaCount: 1
  container:
    image: skryvets/automate-all-things-app
    port: 8080
  service:
    type: ClusterIP
    port: 80
ingress:
  host: my-domain.com # will be overridden at runtime by loadbalancer variable. Please see "deploy-everything.sh" script