name: Helm Publish

on:
  workflow_run:
    workflows: ["Docker Publish"]
    types:
      - completed

jobs:
  push_to_registry:
    if: github.ref == 'refs/heads/main'
    name: Publish helm chart to k8s cluster
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm upgrade automate-all-things-app ./k8s/helm-chart/automate-all-things-app -n automate-all-things-app --set ingress.host=${{ secrets.LOADBALANCER_ADDRESS }}
        kubeconfig: '${{ secrets.KUBECONFIG_FILE }}'
        overrule_existing_kubeconfig: "true"