name: Tests

on: [push]

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17

      - name: Run all tests with Gradle Wrapper
        run: ./gradlew test
